spring:
  application:
    name: Chat-Champions-League-of-Legends
  datasource:
    url: jdbc:h2:mem:chatChampionsLeagueOfLegends
    driver-class-name: org.h2.Driver
    username: chat
    password: ''
  h2:
    console:
      enabled: true